### PR TITLE
New features: (1) log every key press, (2) generic support to log every assignment to a `neurostim.parameter`, even if value unchanged

### PR DESCRIPTION
**Pull request by adammorrissirrommada**
Adds support to log an event every time a key is pressed.

`o.logKey('a')`.

Problem with current implementation: it's logging in cic rather than in the plugin that made the request. To be fixed.

### CODE REVIEW

**Review by bartkrekelberg — CHANGES_REQUESTED** [review]
addKeyStroke is a public funcion so it could be called in some user's code without the logKeyPress input argument.

Specify a default value, or make it protected?

**Comment by adammorrissirrommada** [comment]
oh, good observation. I thought this was already protected and that `plugin.addKey()` was the public method. I think there should only be one, so I am in favour of making `addKeyStroke` protected. I also think that `logKey()` probably shouldn't exist. I made that as a convenience method mostly because positional arguments in `addKey()` are horrible. So a better solution would be to change that to use an inputParser, but with `varargin` to capture arguments and provide backward compatibility. what do you think?

i.e.

```
o.addKey('k','log',true)
'''

**Comment by adammorrissirrommada** [comment]
This remains a work-in-progress. When I get another second to work on it, I will rename the protected `addKeyStroke` and leave a public method with that name and a deprecation error with info in case anyone uses it in their experiment script.

**Comment by adammorrissirrommada** [comment]
I deprecated cic.addKeyStroke. It issues an error:

```
Error using neurostim.cic/error (line 889)
Rethrowing unhandled cic error: '"addKeyStroke" has been deprecated. use "addKey()". see: neurostim.plugin.addKey'
```

**Review by bartkrekelberg — APPROVED** [review]
Looks fine to me. A welcome addition.

**Pull request merged**
